---
# tasks file for deepin-docker

- name: Install dependencies on Ubuntu
  apt:
    name=docker.io
    state=present
  when: "ansible_distribution == 'Ubuntu'"

- name: Install dependencies on Deepin
  apt:
    name=docker-ce
    state=present
  when: "ansible_distribution == 'Deepin GNU/Linux'"

- name: mkdir docker image
  file:
    path={{ image_dir }}
    state=directory

- name: copy dockerfile
  template:
    src=Dockerfile
    dest={{ image_dir }}

- name: create docker image from rootfs
  shell:
    cd {{ image_dir }};
    docker build -t {{ docker_img_name }} .

# name: start docker image
# shell:
#   docker run -ti {{ docker_img_name }} --name docker-test --net=host /bin/bash
#   docker run -ti {{ docker_img_name }} --name docker-test --net=bridge /bin/bash
#   docker run -ti -v /opt/dmdbms:/opt/dmdbms {{ docker_img_name }} --name docker-test --net=host /bin/bash
#   docker run -ti -v /opt/APUSIC:/opt/APUSIC {{ docker_img_name }} --name docker-test --net=host /bin/bash
#   docker run -tdi --privileged --name docker --hostname docker --net=host -v /c00365621:/opt deepin:15 init
#   start oa docker
#   docker run -tdi --privileged --name oad --hostname oad --net=host -v /c00365621:/opt --cpuset-cpus 4-31 --cpuset-mems 0,1 --memory 42949672960 deepin:15 init
#   start db docker
#   docker run -tdi --privileged --name dbd --hostname dbd --net=host -v /c00365621:/opt --cpuset-cpus 32-63 --cpuset-mems 2,3 --memory 66571993088 deepin:15 init
